*Import our Data to see what it contains*

In [2]:
import pandas as pd
whoop_fitness_dataset=pd.read_csv("../data/whoop_fitness_dataset_100k.csv")
whoop_fitness_dataset.head()

,user_id,date,day_of_week,age,gender,weight_kg,height_cm,fitness_level,primary_sport,recovery_score,...,activity_strain,avg_heart_rate,max_heart_rate,activity_calories,hr_zone_1_min,hr_zone_2_min,hr_zone_3_min,hr_zone_4_min,hr_zone_5_min,workout_time_of_day
0,USER_00001,2023-01-01,Sunday,56,Female,53.9,167.2,Beginner,Weight Training,57.8,...,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1,USER_00001,2023-01-02,Monday,56,Female,53.9,167.2,Beginner,Weight Training,62.6,...,7.47,121.2,137.6,371.0,11.9,18.0,15.9,11.6,4.6,Evening
2,USER_00001,2023-01-03,Tuesday,56,Female,53.9,167.2,Beginner,Weight Training,81.5,...,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3,USER_00001,2023-01-04,Wednesday,56,Female,53.9,167.2,Beginner,Weight Training,55.0,...,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
4,USER_00001,2023-01-05,Thursday,56,Female,53.9,167.2,Beginner,Weight Training,62.5,...,15.27,136.4,152.8,623.0,3.7,6.0,13.7,18.6,9.0,Evening

Explore the dataset
Qualitative (Categorical) vs. Quantitative (Numerical) Data

str: qualitative variable / 
int64: quantitative & discrete /
float64: quantitative & continuous

In [3]:
whoop_fitness_dataset.dtypes

user_id                        str
date                           str
day_of_week                    str
age                          int64
gender                         str
weight_kg                  float64
height_cm                  float64
fitness_level                  str
primary_sport                  str
recovery_score             float64
day_strain                 float64
sleep_hours                float64
sleep_efficiency           float64
sleep_performance          float64
light_sleep_hours          float64
rem_sleep_hours            float64
deep_sleep_hours           float64
wake_ups                     int64
time_to_fall_asleep_min    float64
hrv                        float64
resting_heart_rate         float64
hrv_baseline                 int64
rhr_baseline                 int64
respiratory_rate           float64
skin_temp_deviation        float64
calories_burned            float64
workout_completed            int64
activity_type                  str
activity_duration_min        int64
activity_strain            float64
avg_heart_rate             float64
max_heart_rate             float64
activity_calories          float64
hr_zone_1_min              float64
hr_zone_2_min              float64
hr_zone_3_min              float64
hr_zone_4_min              float64
hr_zone_5_min              float64
workout_time_of_day            str
dtype: object

In data analysis, we often convert categorical variable into dummy variable, if the observation belongs to the specified category, the dummy variable indicating the category would equal to 1, otherwise it equals to 0.

Convert a categorical variable to a dummy variable
The variable "gender" only carries two values, Female or Male. We will create dummy variables to capture the categories.

We can use the “pd.get_dummies” function to convert a categorical variable to dummy variable. This function will also omit any missing value.

In [4]:
dummy=pd.get_dummies(whoop_fitness_dataset, columns=['gender'])
dummy.columns

Index(['user_id', 'date', 'day_of_week', 'age', 'weight_kg', 'height_cm',
       'fitness_level', 'primary_sport', 'recovery_score', 'day_strain',
       'sleep_hours', 'sleep_efficiency', 'sleep_performance',
       'light_sleep_hours', 'rem_sleep_hours', 'deep_sleep_hours', 'wake_ups',
       'time_to_fall_asleep_min', 'hrv', 'resting_heart_rate', 'hrv_baseline',
       'rhr_baseline', 'respiratory_rate', 'skin_temp_deviation',
       'calories_burned', 'workout_completed', 'activity_type',
       'activity_duration_min', 'activity_strain', 'avg_heart_rate',
       'max_heart_rate', 'activity_calories', 'hr_zone_1_min', 'hr_zone_2_min',
       'hr_zone_3_min', 'hr_zone_4_min', 'hr_zone_5_min',
       'workout_time_of_day', 'gender_Female', 'gender_Male'],
      dtype='str')

Notice that two variables are created, gender_Female and gender_Male. The original variable gender is deleted.

We can attach the "gender_Male" and "gender_Female" dummy variables back to our whoop_fitness_dataset dataset using the pd.concat function.
axis=1 specifies that we are adding a column to the dataset;
axis=0 indicates adding rows

In [6]:


whoop_fitness_dataset = pd.concat(
    [whoop_fitness_dataset, dummy[['gender_Male', 'gender_Female']]],
    axis=1
)

whoop_fitness_dataset.head()

,user_id,date,day_of_week,age,gender,weight_kg,height_cm,fitness_level,primary_sport,recovery_score,...,max_heart_rate,activity_calories,hr_zone_1_min,hr_zone_2_min,hr_zone_3_min,hr_zone_4_min,hr_zone_5_min,workout_time_of_day,gender_Male,gender_Female
0,USER_00001,2023-01-01,Sunday,56,Female,53.9,167.2,Beginner,Weight Training,57.8,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,False,True
1,USER_00001,2023-01-02,Monday,56,Female,53.9,167.2,Beginner,Weight Training,62.6,...,137.6,371.0,11.9,18.0,15.9,11.6,4.6,Evening,False,True
2,USER_00001,2023-01-03,Tuesday,56,Female,53.9,167.2,Beginner,Weight Training,81.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,False,True
3,USER_00001,2023-01-04,Wednesday,56,Female,53.9,167.2,Beginner,Weight Training,55.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,False,True
4,USER_00001,2023-01-05,Thursday,56,Female,53.9,167.2,Beginner,Weight Training,62.5,...,152.8,623.0,3.7,6.0,13.7,18.6,9.0,Evening,False,True

In [7]:
whoop_fitness_dataset.rename(columns={'gender_Male':'Male','gender_Female':'Female'}, inplace=True)
whoop_fitness_dataset.head()

,user_id,date,day_of_week,age,gender,weight_kg,height_cm,fitness_level,primary_sport,recovery_score,...,max_heart_rate,activity_calories,hr_zone_1_min,hr_zone_2_min,hr_zone_3_min,hr_zone_4_min,hr_zone_5_min,workout_time_of_day,Male,Female
0,USER_00001,2023-01-01,Sunday,56,Female,53.9,167.2,Beginner,Weight Training,57.8,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,False,True
1,USER_00001,2023-01-02,Monday,56,Female,53.9,167.2,Beginner,Weight Training,62.6,...,137.6,371.0,11.9,18.0,15.9,11.6,4.6,Evening,False,True
2,USER_00001,2023-01-03,Tuesday,56,Female,53.9,167.2,Beginner,Weight Training,81.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,False,True
3,USER_00001,2023-01-04,Wednesday,56,Female,53.9,167.2,Beginner,Weight Training,55.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,False,True
4,USER_00001,2023-01-05,Thursday,56,Female,53.9,167.2,Beginner,Weight Training,62.5,...,152.8,623.0,3.7,6.0,13.7,18.6,9.0,Evening,False,True